### ISSUE TITLE
Pax Header Issue

### ISSUE THREAD

**Issue by zserre** [escapestudios-cookbooks/newrelic#162]
Getting an error running the default newrelic recipe on setup in AWS OpsWorks

The error I get is:

```
================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/newrelic/providers/PaxHeader/deployment.rb
================================================================================
 
 
SyntaxError
-----------
/var/lib/aws/opsworks/cache.stage2/cookbooks/newrelic/providers/PaxHeader/deployment.rb:1: syntax error, unexpected tIDENTIFIER, expecting end-of-input
18 gid=1160039685
^
 
 
Cookbook Trace:
---------------
/opt/aws/opsworks/releases/20150304172806_33700020150304172806/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:42:in `class_eval'
/opt/aws/opsworks/releases/20150304172806_33700020150304172806/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:42:in `class_from_file'
/opt/aws/opsworks/releases/20150304172806_33700020150304172806/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/provider/lwrp_base.rb:94:in `build_from_file'
/opt/aws/opsworks/releases/20150304172806_33700020150304172806/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:199:in `load_lwrp_provider'
/opt/aws/opsworks/releases/20150304172806_33700020150304172806/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:190:in `block in load_lwrps_from_cookbook'
/opt/aws/opsworks/releases/20150304172806_33700020150304172806/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:189:in `each'
/opt/aws/opsworks/releases/20150304172806_33700020150304172806/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:189:in `load_lwrps_from_cookbook'
/opt/aws/opsworks/releases/20150304172806_33700020150304172806/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:120:in `block in compile_lwrps'
```

my key is correct and is in proper location 

I think it may have something to do with:

https://tickets.opscode.com/browse/CHEF-4107

**Comment by zserre** [comment]
The way I am including this cookbook is by using it pretty much exactly as described [here](http://blog.newrelic.com/2014/07/31/monitoring-aws-opsworks/)

Also to note it seemed to be working just fine the other day when running and seems to be not working anymore.  I also verified that the error does not occur by just including the Berksfile. However when running `newrelic::default` the error occurs

Moar stack trace

```
Relevant File Content:
----------------------
/opt/aws/opsworks/releases/20150304172806_33700020150304172806/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:
 
35: 
36:        # Loads a given ruby file, and runs class_eval against it in the context of the current
37:        # object.
38:        #
39:        # Raises an IOError if the file cannot be found, or is not readable.
40:        def class_from_file(filename)
41:          if File.exists?(filename) && File.readable?(filename)
42>>           self.class_eval(IO.read(filename), filename, 1)
43:          else
44:            raise IOError, "Cannot open or read #{filename}!"
45:          end
46:        end
47: 
48:      end
49:    end
50:  end
51: 
 
 
[2015-03-28T22:42:16+00:00] ERROR: Running exception handlers
[2015-03-28T22:42:16+00:00] ERROR: Exception handlers complete
[2015-03-28T22:42:16+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2015-03-28T22:42:16+00:00] ERROR: /var/lib/aws/opsworks/cache.stage2/cookbooks/newrelic/providers/PaxHeader/deployment.rb:1: syntax error, unexpected tIDENTIFIER, expecting end-of-input
18 gid=1160039685
^
```

**Comment by peterslivka** [comment]
Just got the very same error. Locking cookbook version to 2.8.0 solved this issue for me, but it's just workaround. Try to update your Beksfile to this:
```
cookbook 'newrelic', '~> 2.8.0'
```

**Comment by zserre** [comment]
thanks @peterslivka that work around worked for me!

Just a note the issue is still happening on other deployments running `2.9.0`

**Comment by pavelpachkovskij** [comment]
same issue

**Comment by dodwyer** [comment]
same issue here as well

**Comment by pavel-d** [comment]
same here

**Comment by djoos** [comment]
Hi all,

I've recently given up of my Windows-machine and started devving on a MBP...
Let me have a look into a workaround so I can get 2.9.0 pushed out properly.

Sorry for the inconvenience!

Kind regards,
David

**Comment by pavel-d** [comment]
@djoos, you might just bump a version and publish cookbook from Linux VM :)

**Comment by TangRufus** [comment]
Same issue here

**Comment by djoos** [comment]
Sorry guys, rushed home from work to watch Belgium (:soccer:) play ;-)
I've just pushed 2.9.1 out from my Linux machine...

I'll close off this issue for now, but please do let me know how it goes!

Kind regards,
David

**Comment by djoos** [comment]
gnutar has now replaced bsdtar on my machine - 2.12.0 just got released this way, so please do let me know if you have any PAX header issues...

Thanks in advance!
