### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by ge1st** [escapestudios-cookbooks/newrelic#183]
I just updated to the latest version (`2.11.2`) of this cookbook from `2.8.0`. I now have a non-ascii character causing my tests to barf.

```
  No Chef resources found, skipping coverage calculation...
/var/lib/jenkins/.rvm/gems/ruby-2.1.5@cookbook-testing/gems/json-1.8.2/lib/json/common.rb:155:in `encode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
	from /var/lib/jenkins/.rvm/gems/ruby-2.1.5@cookbook-testing/gems/json-1.8.2/lib/json/common.rb:155:in `initialize'
	from /var/lib/jenkins/.rvm/gems/ruby-2.1.5@cookbook-testing/gems/json-1.8.2/lib/json/common.rb:155:in `new'
	from /var/lib/jenkins/.rvm/gems/ruby-2.1.5@cookbook-testing/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	from /var/lib/jenkins/.rvm/gems/ruby-2.1.5@cookbook-testing/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:473:in `from_json'
	from /var/lib/jenkins/.rvm/gems/ruby-2.1.5@cookbook-testing/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:29:in `from_json'
	from /var/lib/jenkins/.rvm/gems/ruby-2.1.5@cookbook-testing/gems/ridley-4.1.2/lib/ridley/chef/cookbook.rb:36:in `from_path'
	from /var/lib/jenkins/.rvm/gems/ruby-2.1.5@cookbook-testing/gems/berkshelf-3.2.4/lib/berkshelf/cached_cookbook.rb:15:in `from_store_path'
	from /var/lib/jenkins/.rvm/gems/ruby-2.1.5@cookbook-testing/gems/berkshelf-3.2.4/lib/berkshelf/cookbook_store.rb:108:in `block in cookbooks'
	from /var/lib/jenkins/.rvm/gems/ruby-2.1.5@cookbook-testing/gems/berkshelf-3.2.4/lib/berkshelf/cookbook_store.rb:98:in `collect'
...
```
I can force my rspec run to use `Encoding::UTF_8` and get past this but I can't easily force test-kitchen to do so.

It looks like the character causing the problem is just in a readme file:

```
 newrelic  % ag "[\x80-\xFF]"         
test/fixtures/cookbooks/newrelic_lwrp_test/README.md
18:* ```config_file:``` The New Relic php agent config file, depends on your php external configuration directory; e.g. /etc/php5/conf.d/newrelic.ini, /etc/php5/mods-available/newrelic.ini, [0m¦ Defaults to nil

README.md
256:* `'config_file'` - The New Relic php agent config file, depends on your php external configuration directory; e.g. /etc/php5/conf.d/newrelic.ini, /etc/php5/mods-available/newrelic.ini, [0m¦ Defaults to nil
```
From 996a1d771789771f8e3dfc0f2dd88f0b940a8e80 and e33794738b9901d31cd7c9a828b866656bc53e0d

I'd be awfully grateful if my pull-request and merge are released quickly.

**Comment by ge1st** [comment]
Ok well it's not that critical. After commit this fix on a local branch, I'm now having problems with the cookbooks getting pulled in from the `apt` dependency. They too have non-ascii characters. I've just reverted the version of this cookbook to `2.9.1` in my wrapper, which was the last version before `apt` was introduced, and everything is fine again.
