### ISSUE TITLE
Cannot find module 'concat-stream'

### ISSUE THREAD

**Issue by PurrBiscuit** [escapestudios-cookbooks/newrelic#199]
I've been running into this error recently with the node.js newrelic agent on startup.  Any ideas on what I'm doing wrong?

```
New Relic for Node.js was unable to bootstrap itself due to an error:
Error: Cannot find module 'concat-stream'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/node-app/current/node_modules/newrelic/lib/aws-info.js:6:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/var/www/node-app/current/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/node-app/current/node_modules/newrelic/lib/system-info.js:4:20)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/var/www/node-app/current/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/node-app/current/node_modules/newrelic/lib/collector/facts.js:3:23)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/var/www/node-app/current/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/node-app/current/node_modules/newrelic/lib/collector/api.js:4:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/var/www/node-app/current/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/node-app/current/node_modules/newrelic/lib/agent.js:9:20)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/var/www/node-app/current/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/node-app/current/node_modules/newrelic/index.js:58:17)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/var/www/node-app/current/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/var/www/node-app/current/server/server.coffee:1:1)
  at Object.<anonymous> (/var/www/node-app/current/server/server.coffee:1:1)
  at Module._compile (module.js:456:26)
```

it seems like newrelic agent relies on concat-stream but is this something I have to install before running the nodejs-agent recipe?  I had gotten it to work for a few minutes without any problems and now I can't seem to get it working again...just see this error all the time now.

**Comment by djoos** [comment]
Hi @PurrBiscuit,

thanks for reaching out!

By the sounds of it the issue is not a cookbook issue, but an issue with New Relic for Node.js. It should resolve its dependencies, but perhaps it's safer running this past New Relic support.

Would you be able to run this past NR support and update the issue here with their feedback?

Thanks in advance for your help!

Kind regards,
David
